In [24]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
import numpy as np  

In [40]:
x =np.array([[0,0], [0,1], [1,0], [1,1]], "uint8")
y = np.array([[0], [0], [0], [1]], "uint8")

In [42]:
model = Sequential()
model.add(Dense(units=1, activation='sigmoid', input_dim=2))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [27]:
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [44]:
model.fit(x, y, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7280 - accuracy: 0.7500
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7276 - accuracy: 0.7500
Epoch 3/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7272 - accuracy: 0.7500
Epoch 4/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7268 - accuracy: 0.7500
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7264 - accuracy: 0.7500
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7260 - accuracy: 0.7500
Epoch 7/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7257 - accuracy: 0.7500
Epoch 8/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7253 - accuracy: 0.7500
Epoch 9/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7249 - accuracy: 0.7500
Epoch 10/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7245 - accuracy: 0.7500
Epoch 11/500
1/1 [===========

In [45]:
print(model.layers[0].get_weights())

[array([[0.681947  ],
       [0.05726421]], dtype=float32), array([-0.5079909], dtype=float32)]


In [46]:
model.predict(x)

array([[0.37566465],
       [0.38918802],
       [0.54337966],
       [0.5575489 ]], dtype=float32)

In [47]:
x = [[0,0], [0,1], [1,0], [1,1]]
y = [[0], [0], [0], [1]]

In [49]:
xor = Sequential()
xor.add(Dense(2, input_dim=2, activation='sigmoid'))
xor.add(Dense(1, activation='sigmoid'))
xor.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
xor.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_17 (Dense)             (None, 2)                 6         
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [50]:
xor.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 441ms/step - loss: 0.6795 - accuracy: 0.7500
Epoch 2/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6790 - accuracy: 0.7500
Epoch 3/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6785 - accuracy: 0.7500
Epoch 4/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6781 - accuracy: 0.7500
Epoch 5/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.6776 - accuracy: 0.7500
Epoch 6/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6771 - accuracy: 0.7500
Epoch 7/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6766 - accuracy: 0.7500
Epoch 8/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6761 - accuracy: 0.7500
Epoch 9/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.6757 - accuracy: 0.7500
Epoch 10/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6752 - accuracy: 0.7500
Epoch 11/1000
1/1

In [51]:
xor.get_weights()

[array([[-2.3053412, -1.1277007],
        [-1.1500062, -1.4865497]], dtype=float32),
 array([1.2171401, 1.0929998], dtype=float32),
 array([[-0.89079714],
        [-0.8665794 ]], dtype=float32),
 array([-0.44583955], dtype=float32)]

In [52]:
xor.predict(x)

array([[0.14403608],
       [0.22178471],
       [0.25047982],
       [0.33469075]], dtype=float32)

In [53]:
 from sklearn.datasets import load_breast_cancer
 Data = load_breast_cancer()

In [54]:
print(Data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [55]:
features = Data.data
target = Data.target

print(features.shape)
print(target.shape)

(569, 30)
(569,)


In [63]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(455, 30)
(455,)
(114, 30)
(114,)


In [58]:
from keras.models import Sequential
from keras.layers import Dense

In [59]:
model = Sequential()
model.add(Dense(32, input_dim=30, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation ='sigmoid'))

In [67]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [68]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                992       
_________________________________________________________________
dense_1 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 3,169
Trainable params: 3,169
Non-trainable params: 0
_________________________________________________________________


In [69]:
model.fit(X_train,y_train, epochs=10)

Epoch 1/10
15/15 [==============================] - 14s 2ms/step - loss: 85.8188 - accuracy: 0.6366
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 12.8658 - accuracy: 0.4054
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 3.5699 - accuracy: 0.7944
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 1.2184 - accuracy: 0.8138
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 1.4228 - accuracy: 0.8868
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 0.7333 - accuracy: 0.8930
Epoch 7/10
15/15 [==============================] - 0s 3ms/step - loss: 0.5209 - accuracy: 0.8942
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5411 - accuracy: 0.9034
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.7290 - accuracy: 0.8379
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6268 - accuracy: 0.8497


In [71]:
scores = model.evaluate(X_test, y_test)
print(scores)

4/4 [==============================] - 1s 3ms/step - loss: 0.4033 - accuracy: 0.8246
[0.4032837748527527, 0.8245614171028137]


In [78]:
predictions = model.predict(X_test)
label=[]
for pred in predictions:
  if pred>= 0.5:
    print("Malignent")
  else:
    print("Benign")

Benign
Benign
Malignent
Malignent
Benign
Benign
Benign
Benign
Malignent
Benign
Malignent
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Benign
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Benign
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Benign
Benign
Benign
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Benign
Benign
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Benign
Benign
Benign
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Malignent
Benign
Benign
Malignent
Benign
Benign
Malignent
Malignent
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Malignent
Malignent
Benign
Benign
